# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a3d793513467715f727b9509ff20657c074ff4228c6550bfbb65e75637f480630bcc48bba217bb106393f6513def3598c29532affd97924991d1710218cd371a

test:
  secret_key_base: 666c779311f7b1050fccd944eb1d215d54aa9fc6b3edcce7c30a529c0bed521633589de97c59d6174d15e6bf205d3a2ed8837a1c03c30e2facac2f436876cdfe

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
